<?php
declare(strict_types=1);
spl_autoload_register(static function(string $class):void{$prefix='ImAuthenticator\\';if(!str_starts_with($class,$prefix))return;$path=dirname(__DIR__).'/src/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($path))require$path;});
use ImAuthenticator\AuditLog;use ImAuthenticator\CryptoService;use ImAuthenticator\Database;use ImAuthenticator\MfaService;use ImAuthenticator\Security;use ImAuthenticator\UserImportService;use ImAuthenticator\UserMergeService;
function opcheck(bool $ok,string $msg):void{if(!$ok){fwrite(STDERR,"FAIL: $msg\n");exit(1);}fwrite(STDOUT,"OK: $msg\n");}
$env=static function(string $n,string $d):string{$v=getenv($n);return$v===false?$d:$v;};$db=new Database(['dsn'=>$env('TEST_DB_DSN','mysql:host=127.0.0.1;dbname=imauth_ci;charset=utf8mb4'),'user'=>$env('TEST_DB_USER','root'),'pass'=>$env('TEST_DB_PASS','')]);$audit=new AuditLog($db);$key=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$crypto=new CryptoService(['app_key'=>$key]);$mfa=new MfaService($db,$crypto,$audit,['issuer'=>'https://auth.example.test']);$import=new UserImportService($db,$audit);$merge=new UserMergeService($db,$audit);$suffix=bin2hex(random_bytes(4));$hash=password_hash('Operational-Test-Password-123!',PASSWORD_ARGON2ID);
$db->execute("INSERT INTO users(uuid,name,username,email,password_hash,is_admin,enabled,lifecycle_status) VALUES(?,?,?,?,?,1,1,'active')",[Security::uuidV4(),'Ops Admin','ops-admin-'.$suffix,'ops-admin-'.$suffix.'@example.test',$hash]);$admin=$db->lastInsertId();
$db->execute("INSERT INTO users(uuid,name,username,email,password_hash,enabled,lifecycle_status) VALUES(?,?,?,?,?,1,'active')",[Security::uuidV4(),'Target User','target-'.$suffix,'target-'.$suffix.'@example.test',$hash]);$target=$db->lastInsertId();
$setup=$mfa->beginTotp($target,'CI TOTP');
function b32decode_test(string $s):string{$alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';foreach(str_split(strtoupper($s))as$c){$p=strpos($alphabet,$c);if($p===false)continue;$bits.=str_pad(decbin($p),5,'0',STR_PAD_LEFT);}$out='';foreach(str_split($bits,8)as$chunk)if(strlen($chunk)===8)$out.=chr(bindec($chunk));return$out;}
function totp_test(string $secret):string{$key=b32decode_test($secret);$counter=intdiv(time(),30);$binary=pack('N2',($counter>>32)&0xffffffff,$counter&0xffffffff);$h=hash_hmac('sha1',$binary,$key,true);$o=ord($h[19])&0x0f;$n=((ord($h[$o])&0x7f)<<24)|((ord($h[$o+1])&0xff)<<16)|((ord($h[$o+2])&0xff)<<8)|(ord($h[$o+3])&0xff);return str_pad((string)($n%1000000),6,'0',STR_PAD_LEFT);}
$code=totp_test((string)$setup['secret']);$mfa->confirmTotp($target,(int)$setup['method_id'],$code);opcheck($mfa->verify($target,$code),'TOTP enrollment and verification works');$backup=$mfa->regenerateBackupCodes($target);opcheck(count($backup)===10&&$mfa->verify($target,$backup[0]),'backup code is generated and consumed');
$rows=[['name'=>'Imported User','email'=>'imported-'.$suffix.'@example.test','username'=>'imported-'.$suffix,'groups'=>'IT;Monitoring','attr.department'=>'IT','_source_row'=>2]];$result=$import->importRows($rows,'ci.csv','csv',$admin,'skip');opcheck((int)$result['summary']['created']===1,'CSV-style import creates a user');$sourceRow=$db->one('SELECT id,enabled,lifecycle_status FROM users WHERE email=?',['imported-'.$suffix.'@example.test']);opcheck($sourceRow!==null,'imported user exists');$source=(int)$sourceRow['id'];$required=$db->one("SELECT COUNT(*) AS c FROM required_actions WHERE user_id=? AND action_type IN ('change_password','verify_email')",[$source]);opcheck((int)$required['c']===2,'import creates password and e-mail required actions');
$db->execute("INSERT INTO applications(uuid,name,slug,url,client_id,client_type,access_policy,enabled) VALUES(?,?,?,?,?,'confidential','none',1)",[Security::uuidV4(),'Merge App','merge-app-'.$suffix,'https://merge.example.test','merge_'.$suffix]);$app=$db->lastInsertId();$db->execute("INSERT INTO application_users(application_id,user_id,enabled,grant_source) VALUES(?,?,1,'manual')",[$app,$source]);$group=$db->one("SELECT id FROM user_groups WHERE name='IT'");opcheck($group!==null,'import assigns groups');
$merge->merge($source,$target,$admin,'CI duplicate merge');$disabled=$db->one('SELECT enabled,lifecycle_status FROM users WHERE id=?',[$source]);opcheck(!(bool)$disabled['enabled']&&$disabled['lifecycle_status']==='disabled','source account is retained but disabled');opcheck($db->one('SELECT 1 FROM application_users WHERE application_id=? AND user_id=?',[$app,$target])!==null,'application access is transferred');opcheck($db->one('SELECT 1 FROM group_members WHERE group_id=? AND user_id=?',[(int)$group['id'],$target])!==null,'group membership is transferred');opcheck($db->one("SELECT 1 FROM audit_log WHERE action='users.merged' AND subject_user_id=? ORDER BY id DESC LIMIT 1",[$target])!==null,'merge is audited');
fwrite(STDOUT,"Operational identity smoke test passed.\n");
