<?php
declare(strict_types=1);
spl_autoload_register(static function(string$class):void{$p='ImAuthenticator\\';if(!str_starts_with($class,$p))return;$f=dirname(__DIR__).'/src/'.str_replace('\\','/',substr($class,strlen($p))).'.php';if(is_file($f))require$f;});
use ImAuthenticator\AuditLog;use ImAuthenticator\Database;use ImAuthenticator\EventService;use ImAuthenticator\MailQueueService;use ImAuthenticator\SecretExpiryService;use ImAuthenticator\Security;
function okSched(bool$c,string$m):void{if(!$c){fwrite(STDERR,"FAIL: {$m}\n");exit(1);}fwrite(STDOUT,"OK: {$m}\n");}
$env=static fn(string$n,string$d)=>(getenv($n)===false?$d:(string)getenv($n));$db=new Database(['dsn'=>$env('TEST_DB_DSN','mysql:host=127.0.0.1;dbname=imauth_ci;charset=utf8mb4'),'user'=>$env('TEST_DB_USER','root'),'pass'=>$env('TEST_DB_PASS','')]);$audit=new AuditLog($db);$events=new EventService($db);$mail=new MailQueueService($db,$audit,['mail'=>['transport'=>'log']]);$svc=new SecretExpiryService($db,$mail,$events,$audit);
$s=bin2hex(random_bytes(4));$hash=password_hash('Scheduler-test-password',PASSWORD_ARGON2ID);$db->execute("INSERT INTO users(uuid,name,username,email,password_hash,is_admin,enabled,lifecycle_status) VALUES(?,?,?,?,?,1,1,'active')",[Security::uuidV4(),'Scheduler Admin','sched-'.$s,'sched-'.$s.'@example.test',$hash]);$admin=$db->lastInsertId();$db->execute("INSERT INTO applications(uuid,name,slug,url,client_id,client_type,access_policy,enabled) VALUES(?,?,?,?,?,'confidential','none',1)",[Security::uuidV4(),'Expiry App','expiry-'.$s,'https://expiry.example.test','ima_expiry_'.$s]);$app=$db->lastInsertId();$db->execute('INSERT INTO application_owners(application_id,user_id,is_primary,created_by) VALUES(?,?,1,?)',[$app,$admin,$admin]);$db->execute('INSERT INTO client_secrets(application_id,secret_hash,secret_hint,valid_until,created_by) VALUES(?,?,?,?,?)',[$app,Security::secretHash('secret-'.$s),'ims_test',date('Y-m-d H:i:s',time()+6*86400),$admin]);
$r=$svc->scan();okSched($r['events']===1,'expiring current client secret emits one event');okSched($r['emails_queued']===1,'expiring secret queues owner e-mail');$r2=$svc->scan();okSched($r2['events']===0&&$r2['emails_queued']===0,'same threshold is deduplicated');$event=$db->one("SELECT payload_json FROM event_outbox WHERE event_type='application.secret.expiring' ORDER BY id DESC LIMIT 1");$payload=$event?json_decode((string)$event['payload_json'],true):null;okSched(is_array($payload)&&($payload['threshold_days']??null)===7&&($payload['severity']??null)==='critical','7-day secret alert is critical');
$jobs=array_column($db->all("SELECT job_key FROM scheduled_jobs WHERE job_key LIKE 'system:%'"),'job_key');foreach(['system:secret-expiry','system:housekeeping','system:delivery','system:mail','system:signing-key-rotation']as$k)okSched(in_array($k,$jobs,true),'system scheduler job exists: '.$k);fwrite(STDOUT,"Scheduler and secret expiry smoke test passed.\n");
