<?php
declare(strict_types=1);

spl_autoload_register(static function(string $class):void{$prefix='ImAuthenticator\\';if(!str_starts_with($class,$prefix))return;$path=dirname(__DIR__).'/src/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($path))require$path;});
use ImAuthenticator\ApplicationAccessService;use ImAuthenticator\ApplicationAdminService;use ImAuthenticator\AuditLog;use ImAuthenticator\ConditionalAccessService;use ImAuthenticator\Database;use ImAuthenticator\OidcService;use ImAuthenticator\Security;
function scheck(bool $ok,string $msg):void{if(!$ok){fwrite(STDERR,"FAIL: $msg\n");exit(1);}fwrite(STDOUT,"OK: $msg\n");}
$env=static function(string$n,string$d):string{$v=getenv($n);return$v===false?$d:$v;};$db=new Database(['dsn'=>$env('TEST_DB_DSN','mysql:host=127.0.0.1;dbname=imauth_ci;charset=utf8mb4'),'user'=>$env('TEST_DB_USER','root'),'pass'=>$env('TEST_DB_PASS','')]);$audit=new AuditLog($db);$access=new ApplicationAccessService($db,$audit);$conditional=new ConditionalAccessService($db,$access);$admins=new ApplicationAdminService($db);$suffix=bin2hex(random_bytes(4));$hash=password_hash('Session-Test-Password-123!',PASSWORD_ARGON2ID);
$db->execute("INSERT INTO users(uuid,name,username,email,password_hash,enabled,lifecycle_status) VALUES(?,?,?,?,?,1,'active')",[Security::uuidV4(),'Session User','sess-'.$suffix,'sess-'.$suffix.'@example.test',$hash]);$userId=$db->lastInsertId();$secret='ims_test_'.$suffix;$clientId='ima_session_'.$suffix;$redirect='https://client.example.test/callback';$db->execute("INSERT INTO applications(uuid,name,slug,url,client_id,client_secret_hash,client_type,access_policy,enabled,session_ttl_seconds,max_concurrent_sessions) VALUES(?,?,?,?,?,?,'confidential','none',1,900,1)",[Security::uuidV4(),'Session App','session-'.$suffix,'https://client.example.test',$clientId,Security::secretHash($secret)]);$appId=$db->lastInsertId();$db->execute('INSERT INTO application_redirect_uris(application_id,redirect_uri) VALUES(?,?)',[$appId,$redirect]);$db->execute("INSERT INTO application_scopes(application_id,scope) VALUES(?,'openid')",[$appId]);$access->grantUser($appId,$userId,null);
$key=openssl_pkey_new(['private_key_bits'=>2048,'private_key_type'=>OPENSSL_KEYTYPE_RSA]);if($key===false)throw new RuntimeException('keygen');openssl_pkey_export($key,$pem);$keyPath=sys_get_temp_dir().'/imauth-session-'.$suffix.'.pem';file_put_contents($keyPath,$pem);$oidc=new OidcService($db,$access,$conditional,$audit,['issuer'=>'https://auth.example.test','keys'=>['private'=>$keyPath,'kid'=>'test']]);$_SESSION=['auth_level'=>1,'auth_time'=>time()];$app=$oidc->client($clientId);if(!$app)throw new RuntimeException('app_missing');$code=$oidc->createAuthorizationCode($app,$userId,$redirect,['openid'],null,null,null);$tokens=$oidc->exchangeAuthorizationCode(['client_id'=>$clientId,'client_secret'=>$secret,'code'=>$code,'redirect_uri'=>$redirect],null);scheck((int)$tokens['expires_in']<=900&&(int)$tokens['expires_in']>800,'per-application session TTL shortens access token');$accessRow=$db->one('SELECT expires_at FROM oauth_access_tokens WHERE token_hash=?',[Security::tokenHash((string)$tokens['access_token'])]);scheck($accessRow!==null&&strtotime((string)$accessRow['expires_at'])-time()<=900,'database access-token expiry follows policy');$refreshRow=$db->one('SELECT oidc_session_id,expires_at FROM oauth_refresh_tokens WHERE token_hash=?',[Security::tokenHash((string)$tokens['refresh_token'])]);scheck((int)($refreshRow['oidc_session_id']??0)>0,'refresh token is bound to OIDC session');$sessionId=(int)$refreshRow['oidc_session_id'];$count=$db->one('SELECT COUNT(*) AS c FROM oidc_sessions WHERE application_id=? AND user_id=? AND revoked_at IS NULL',[$appId,$userId]);scheck((int)$count['c']===1,'initial login creates one OIDC session');$new=$oidc->refresh(['client_id'=>$clientId,'client_secret'=>$secret,'refresh_token'=>$tokens['refresh_token']],null);$newRow=$db->one('SELECT oidc_session_id FROM oauth_refresh_tokens WHERE token_hash=?',[Security::tokenHash((string)$new['refresh_token'])]);scheck((int)$newRow['oidc_session_id']===$sessionId,'refresh rotation preserves session identity');$count=$db->one('SELECT COUNT(*) AS c FROM oidc_sessions WHERE application_id=? AND user_id=? AND revoked_at IS NULL',[$appId,$userId]);scheck((int)$count['c']===1,'refresh does not create a concurrent session');$blocked=false;try{$oidc->createAuthorizationCode($app,$userId,$redirect,['openid'],null,null,null);}catch(RuntimeException $e){$blocked=$e->getMessage()==='access_denied';}scheck($blocked,'concurrent session limit blocks a second login');
$db->execute("INSERT INTO users(uuid,name,username,email,password_hash,enabled,lifecycle_status) VALUES(?,?,?,?,?,1,'active')",[Security::uuidV4(),'Delegated Admin','deleg-'.$suffix,'deleg-'.$suffix.'@example.test',$hash]);$deleg=$db->lastInsertId();$db->execute('INSERT INTO application_admins(application_id,user_id,permissions_json) VALUES(?,?,?)',[$appId,$deleg,json_encode(['manage_users'=>true],JSON_THROW_ON_ERROR)]);scheck($admins->canManage($deleg,$appId,'manage'),'granular delegated admin can see managed application');scheck($admins->canManage($deleg,$appId,'manage_users'),'delegated user permission is honored');scheck(!$admins->canManage($deleg,$appId,'manage_security'),'unassigned delegated permission is denied');@unlink($keyPath);fwrite(STDOUT,"Session policy smoke test passed.\n");
