<?php
declare(strict_types=1);

use ImAuthenticator\Security;
use ImAuthenticator\Web;

$services=require dirname(__DIR__).'/src/bootstrap.php';extract($services,EXTR_SKIP);$user=$auth->requireUser();$message='';
if(strtoupper($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 Security::requireCsrf($_POST['_csrf']??null);$action=(string)($_POST['action']??'');
 try{
  if($action==='create'){$reviews->create((int)$_POST['application_id'],(int)($_POST['reviewer_user_id']??$user['id']),(int)$user['id'],trim((string)$_POST['name']),trim((string)($_POST['due_at']??''))?:null);$message='<div class="alert success">Access Review został utworzony.</div>';}
  if($action==='decide'){$reviews->decide((int)$_POST['review_id'],(int)$_POST['user_id'],(string)$_POST['decision'],(int)$user['id'],trim((string)($_POST['note']??''))?:null);$message='<div class="alert success">Decyzja została zapisana.</div>';}
  if($action==='complete'){$reviews->complete((int)$_POST['review_id'],(int)$user['id']);$message='<div class="alert success">Przegląd został zakończony.</div>';}
 }catch(Throwable $e){$message='<div class="alert danger">'.Web::e($e->getMessage()).'</div>';}
}
$apps=$db->all('SELECT id,name FROM applications WHERE deleted_at IS NULL ORDER BY name');$users=$db->all("SELECT id,name,email FROM users WHERE enabled=1 AND lifecycle_status='active' ORDER BY name");$appOptions='';foreach($apps as $a)if($appAdmins->canManage((int)$user['id'],(int)$a['id'],'access_reviews'))$appOptions.='<option value="'.(int)$a['id'].'">'.Web::e($a['name']).'</option>';$userOptions='';foreach($users as $u)$userOptions.='<option value="'.(int)$u['id'].'">'.Web::e($u['name'].' — '.$u['email']).'</option>';
$reviewRows='';foreach($db->all("SELECT ar.*,a.name AS app_name,r.name AS reviewer_name FROM access_reviews ar JOIN applications a ON a.id=ar.application_id LEFT JOIN users r ON r.id=ar.reviewer_user_id ORDER BY ar.created_at DESC LIMIT 100") as $r){if(!$appAdmins->canManage((int)$user['id'],(int)$r['application_id'],'access_reviews')&&(int)$r['reviewer_user_id']!==(int)$user['id'])continue;$pending=$db->one("SELECT COUNT(*) AS c FROM access_review_items WHERE access_review_id=? AND decision='pending'",[(int)$r['id']]);$reviewRows.='<tr><td>'.Web::e($r['app_name']).'</td><td>'.Web::e($r['name']).'</td><td>'.Web::e($r['reviewer_name']?:'—').'</td><td>'.Web::e($r['status']).'</td><td>'.(int)($pending['c']??0).'</td><td><a href="/admin/access-reviews?review='.(int)$r['id'].'">Otwórz</a></td></tr>';}
$detail='';$reviewId=(int)($_GET['review']??0);if($reviewId>0){$rev=$db->one('SELECT * FROM access_reviews WHERE id=?',[$reviewId]);if($rev&&($appAdmins->canManage((int)$user['id'],(int)$rev['application_id'],'access_reviews')||(int)$rev['reviewer_user_id']===(int)$user['id'])){$items='';foreach($db->all('SELECT ari.*,u.name,u.email FROM access_review_items ari JOIN users u ON u.id=ari.user_id WHERE ari.access_review_id=? ORDER BY u.name',[$reviewId]) as $i){$items.='<tr><td>'.Web::e($i['name']).'</td><td>'.Web::e($i['email']).'</td><td>'.Web::e($i['decision']).'</td><td><form method="post"><input type="hidden" name="_csrf" value="'.Web::e(Security::csrfToken()).'"><input type="hidden" name="review_id" value="'.$reviewId.'"><input type="hidden" name="user_id" value="'.(int)$i['user_id'].'"><input name="note" placeholder="Notatka"><button name="action" value="decide" formaction="/admin/access-reviews"><span hidden></span>Zapisz</button><button name="decision" value="keep">Utrzymaj</button><button name="decision" value="revoke">Odbierz</button></form></td></tr>';}$detail='<section class="card"><h2>Elementy przeglądu</h2><div class="table-wrap"><table><thead><tr><th>Użytkownik</th><th>E-mail</th><th>Decyzja</th><th>Akcje</th></tr></thead><tbody>'.$items.'</tbody></table></div><form method="post"><input type="hidden" name="_csrf" value="'.Web::e(Security::csrfToken()).'"><input type="hidden" name="review_id" value="'.$reviewId.'"><button name="action" value="complete">Zakończ przegląd</button></form></section>';}}
$content='<div class="page-head"><div><h1>Access Reviews</h1><p>Okresowa recertyfikacja dostępu użytkowników.</p></div></div>'.$message.($appOptions!==''?'<section class="card"><h2>Nowy przegląd</h2><form method="post"><input type="hidden" name="_csrf" value="'.Web::e(Security::csrfToken()).'"><label>Nazwa<input name="name" required></label><label>Aplikacja<select name="application_id">'.$appOptions.'</select></label><label>Recenzent<select name="reviewer_user_id">'.$userOptions.'</select></label><label>Termin<input type="datetime-local" name="due_at"></label><button class="primary" name="action" value="create">Utwórz</button></form></section>':'').'<div class="table-wrap"><table><thead><tr><th>Aplikacja</th><th>Nazwa</th><th>Recenzent</th><th>Status</th><th>Oczekujące</th><th></th></tr></thead><tbody>'.$reviewRows.'</tbody></table></div>'.$detail;
Web::page('Access Reviews',$content,$user);
