<?php
declare(strict_types=1);

use ImAuthenticator\Security;
use ImAuthenticator\Web;

$services=require dirname(__DIR__).'/src/bootstrap.php';extract($services,EXTR_SKIP);$admin=$auth->requireAdmin();$message='';
if(strtoupper($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 Security::requireCsrf($_POST['_csrf']??null);$action=(string)($_POST['action']??'');
 try{
  if($action==='create_account'){$org=(int)($_POST['organization_id']??0);$id=$apiKeys->createServiceAccount(trim((string)$_POST['name']),trim((string)($_POST['description']??''))?:null,(int)$admin['id'],$org>0?$org:null);$message='<div class="alert success">Konto techniczne zostało utworzone.</div>';}
  if($action==='create_key'){$account=(int)($_POST['service_account_id']??0);$scopes=is_array($_POST['scopes']??null)?array_map('strval',$_POST['scopes']):[];$until=trim((string)($_POST['valid_until']??''));$until=$until!==''?date('Y-m-d H:i:s',strtotime($until)):null;$raw=$apiKeys->createKey($account,$scopes,(int)$admin['id'],$until);$_SESSION['new_api_key']=$raw;$message='<div class="alert success">API key został utworzony. Skopiuj go teraz.</div>';}
  if($action==='revoke_key'){$apiKeys->revokeKey((int)$_POST['key_id'],(int)$admin['id']);$message='<div class="alert success">API key został unieważniony.</div>';}
  if($action==='disable_account'){$id=(int)$_POST['service_account_id'];$db->execute('UPDATE service_accounts SET enabled=0 WHERE id=?',[$id]);$db->execute('UPDATE api_keys SET revoked_at=COALESCE(revoked_at,NOW()) WHERE service_account_id=?',[$id]);$audit->write('service_account.disabled','success',(int)$admin['id'],null,null,null,['service_account_id'=>$id]);$message='<div class="alert success">Konto techniczne i jego klucze zostały wyłączone.</div>';}
 }catch(Throwable $e){$message='<div class="alert danger">'.Web::e($e->getMessage()).'</div>';}
}
$new=$_SESSION['new_api_key']??null;unset($_SESSION['new_api_key']);$secret=$new?'<section class="card"><h2>Nowy API key</h2><code class="secret">'.Web::e($new).'</code><p>Klucz jest wyświetlany tylko raz.</p></section>':'';
$orgOptions='<option value="0">Globalne</option>';foreach($db->all("SELECT id,name FROM organizations WHERE status='active' ORDER BY name") as $o)$orgOptions.='<option value="'.(int)$o['id'].'">'.Web::e($o['name']).'</option>';
$accounts=$db->all('SELECT s.*,o.name AS org_name FROM service_accounts s LEFT JOIN organizations o ON o.id=s.organization_id ORDER BY s.created_at DESC');$accountOptions='';$rows='';foreach($accounts as $a){if((bool)$a['enabled'])$accountOptions.='<option value="'.(int)$a['id'].'">'.Web::e($a['name']).'</option>';$keys=$db->all('SELECT id,key_prefix,scopes_json,valid_until,last_used_at,revoked_at FROM api_keys WHERE service_account_id=? ORDER BY created_at DESC',[(int)$a['id']]);$keyHtml='';foreach($keys as $k)$keyHtml.='<div><code>'.Web::e($k['key_prefix']).'…</code> '.Web::e($k['scopes_json']?:'[]').' · '.Web::e($k['revoked_at']?'unieważniony':($k['valid_until']&&strtotime((string)$k['valid_until'])<=time()?'wygasły':'aktywny')).(!$k['revoked_at']?'<form method="post" class="inline"><input type="hidden" name="_csrf" value="'.Web::e(Security::csrfToken()).'"><input type="hidden" name="key_id" value="'.(int)$k['id'].'"><button name="action" value="revoke_key">Unieważnij</button></form>':'').'</div>';$rows.='<tr><td>'.Web::e($a['name']).'</td><td>'.Web::e($a['org_name']?:'Globalne').'</td><td>'.((bool)$a['enabled']?'Aktywne':'Wyłączone').'</td><td>'.$keyHtml.'</td><td>'.((bool)$a['enabled']?'<form method="post" class="inline"><input type="hidden" name="_csrf" value="'.Web::e(Security::csrfToken()).'"><input type="hidden" name="service_account_id" value="'.(int)$a['id'].'"><button name="action" value="disable_account">Wyłącz</button></form>':'').'</td></tr>';}
$content='<div class="page-head"><div><h1>Service Accounts / API Keys</h1><p>Konta techniczne do Event API, SIEM i automatyzacji. Klucze są przechowywane wyłącznie jako hash.</p></div></div>'.$message.$secret.'<div class="grid-2"><section class="card"><h2>Nowe konto techniczne</h2><form method="post"><input type="hidden" name="_csrf" value="'.Web::e(Security::csrfToken()).'"><label>Nazwa<input name="name" required></label><label>Opis<textarea name="description"></textarea></label><label>Organizacja<select name="organization_id">'.$orgOptions.'</select></label><button class="primary" name="action" value="create_account">Utwórz</button></form></section><section class="card"><h2>Nowy API key</h2><form method="post"><input type="hidden" name="_csrf" value="'.Web::e(Security::csrfToken()).'"><label>Konto<select name="service_account_id" required>'.$accountOptions.'</select></label><label><input type="checkbox" name="scopes[]" value="events.read" checked> events.read</label><label><input type="checkbox" name="scopes[]" value="audit.read"> audit.read</label><label><input type="checkbox" name="scopes[]" value="users.read"> users.read</label><label><input type="checkbox" name="scopes[]" value="applications.read"> applications.read</label><label>Ważny do<input type="datetime-local" name="valid_until"></label><button class="primary" name="action" value="create_key">Generuj API key</button></form></section></div><div class="table-wrap"><table><thead><tr><th>Konto</th><th>Organizacja</th><th>Status</th><th>Klucze</th><th></th></tr></thead><tbody>'.$rows.'</tbody></table></div>';
Web::page('Service Accounts',$content,$admin);
