<?php
declare(strict_types=1);
use ImAuthenticator\Security;
use ImAuthenticator\Web;
$services=require dirname(__DIR__).'/src/bootstrap.php';extract($services,EXTR_SKIP);$admin=$auth->requireAdmin();$message='';
if(strtoupper($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 Security::requireCsrf($_POST['_csrf']??null);
 try{$file=$_FILES['import_file']??null;if(!is_array($file)||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('upload_failed');$name=(string)($file['name']??'users.csv');$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));if(!in_array($ext,['csv','xlsx'],true))throw new RuntimeException('only_csv_xlsx_supported');$result=$userImport->importFile((string)$file['tmp_name'],$name,$ext,(int)$admin['id'],(string)($_POST['duplicate_mode']??'skip'));$message='<div class="alert success">Import zakończony. Utworzono: '.(int)$result['summary']['created'].', zaktualizowano: '.(int)$result['summary']['updated'].', duplikaty: '.(int)$result['summary']['duplicate'].', błędy: '.(int)$result['summary']['failed'].'.</div>';}catch(Throwable $e){$message='<div class="alert danger">'.Web::e($e->getMessage()).'</div>';}
}
$rows='';foreach($db->all('SELECT j.*,u.email AS actor_email FROM user_import_jobs j LEFT JOIN users u ON u.id=j.created_by ORDER BY j.id DESC LIMIT 30') as $job){$summary=json_decode((string)($job['summary_json']??'{}'),true)?:[];$rows.='<tr><td>'.Web::e($job['file_name']).'</td><td>'.Web::e($job['format']).'</td><td>'.Web::e($job['status']).'</td><td>'.Web::e($job['actor_email']?:'—').'</td><td>'.Web::e($job['created_at']).'</td><td>'.Web::e(json_encode($summary,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)).'</td></tr>';}
if($rows==='')$rows='<tr><td colspan="6" class="empty">Brak importów.</td></tr>';
$content='<div class="page-head"><div><h1>Import użytkowników</h1><p>CSV lub XLSX. Maksymalnie 10 MB. Obsługiwane kolumny: name/nazwa, email, username/login, enabled, groups, roles, account_starts_at, account_ends_at oraz attr.&lt;nazwa&gt;.</p></div><a class="button" href="/admin/users/merge">Scal użytkowników</a></div>'.$message.'<section class="card"><form method="post" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="'.Web::e(Security::csrfToken()).'"><label>Plik<input type="file" name="import_file" accept=".csv,.xlsx" required></label><label>Duplikaty<select name="duplicate_mode"><option value="skip">Pomiń</option><option value="update">Aktualizuj istniejącego użytkownika</option></select></label><div class="alert warning">Import nie przyjmuje haseł. Nowe konta otrzymują losowy, nieznany sekret i Required Actions: zmiana hasła oraz weryfikacja e-mail. Logowanie początkowe może odbyć się przez magic link lub skonfigurowanego zewnętrznego IdP.</div><button class="primary">Importuj</button></form></section><div class="table-wrap"><table><thead><tr><th>Plik</th><th>Format</th><th>Status</th><th>Administrator</th><th>Data</th><th>Podsumowanie</th></tr></thead><tbody>'.$rows.'</tbody></table></div>';
Web::page('Import użytkowników',$content,$admin);
