<?php
declare(strict_types=1);

use ImAuthenticator\Security;
use ImAuthenticator\Web;

$services = require dirname(__DIR__) . '/src/bootstrap.php';
$auth = $services['auth'];
$admin = $auth->requireAdmin();

$content = '<div class="page-head"><div><h1>Dodaj aplikację</h1><p>Kreator klienta OAuth/OpenID Connect.</p></div><a class="button" href="/admin/applications">Anuluj</a></div>';
$content .= '<form method="post" action="/admin/applications" id="appWizard" class="card wizard"><input type="hidden" name="_csrf" value="'.Web::e(Security::csrfToken()).'">';
$content .= '<section class="wizard-step active" data-step="1"><div class="step-label">Krok 1 z 5</div><h2>Dane aplikacji</h2><label>Nazwa aplikacji<input name="name" required></label><label>Opis<textarea name="description" rows="3"></textarea></label><label>Adres aplikacji<input type="url" name="url" placeholder="https://xyz.example.com" required></label><label>Ikona/logo URL<input type="url" name="icon"></label><label>Typ aplikacji<select name="app_type" id="appType"><option value="website">Strona WWW</option><option value="wordpress">WordPress</option><option value="php">Własna aplikacja PHP</option><option value="spa">SPA</option><option value="mobile">Aplikacja mobilna</option><option value="oidc" selected>Generic OpenID Connect</option><option value="m2m">Machine-to-Machine</option></select></label></section>';
$content .= '<section class="wizard-step" data-step="2"><div class="step-label">Krok 2 z 5</div><h2>Typ integracji</h2><label>Integracja<select name="integration_type" id="integrationType"><option value="generic_oidc">Generic OpenID Connect</option><option value="wordpress_oidc">WordPress / OpenID Connect</option><option value="public_pkce">Public Client + PKCE</option><option value="client_credentials">Machine-to-Machine</option></select></label><div class="hint" id="integrationHint">Confidential Client z Authorization Code.</div></section>';
$content .= '<section class="wizard-step" data-step="3"><div class="step-label">Krok 3 z 5</div><h2>Callback / Redirect URI</h2><label>Redirect URI — jeden na linię<textarea name="redirect_uris" id="redirectUris" rows="5" placeholder="https://xyz.example.com/oauth/callback" required></textarea></label><div class="hint" id="redirectHint">Wildcardy są zabronione. Wymagany jest HTTPS, z wyjątkiem localhost do developmentu.</div></section>';
$content .= '<section class="wizard-step" data-step="4"><div class="step-label">Krok 4 z 5</div><h2>Generowanie klienta</h2><p>System wygeneruje kryptograficznie Client ID i — dla confidential client — Client Secret. Administrator nie wpisuje ich ręcznie.</p><label>Scopes<input name="scopes" id="scopePreview" value="openid profile email roles" readonly></label></section>';
$content .= '<section class="wizard-step" data-step="5"><div class="step-label">Krok 5 z 5</div><h2>Dostęp użytkowników</h2><label>Polityka dostępu<select name="access_policy"><option value="none" selected>Brak dostępu — administrator musi przypisać użytkowników</option><option value="all">Wszyscy użytkownicy</option><option value="users">Wybrani użytkownicy</option><option value="groups">Wybrane grupy</option><option value="roles">Wybrane role</option><option value="mixed">Reguły mieszane</option></select></label><div class="alert warning">Domyślna polityka nie udostępnia aplikacji żadnemu użytkownikowi.</div></section>';
$content .= '<div class="wizard-actions"><button type="button" id="prevStep">Wstecz</button><button type="button" class="primary" id="nextStep">Dalej</button><button type="submit" class="primary hidden" id="createApp">Utwórz aplikację</button></div></form>';
$content .= '<script>let s=1;const steps=[...document.querySelectorAll(".wizard-step")],next=document.getElementById("nextStep"),prev=document.getElementById("prevStep"),create=document.getElementById("createApp"),type=document.getElementById("appType"),integration=document.getElementById("integrationType"),redirects=document.getElementById("redirectUris"),redirectHint=document.getElementById("redirectHint"),scope=document.getElementById("scopePreview"),hint=document.getElementById("integrationHint");function show(){steps.forEach(x=>x.classList.toggle("active",Number(x.dataset.step)===s));prev.disabled=s===1;next.classList.toggle("hidden",s===5);create.classList.toggle("hidden",s!==5)}function preset(){integration.value=type.value==="wordpress"?"wordpress_oidc":(["spa","mobile"].includes(type.value)?"public_pkce":(type.value==="m2m"?"client_credentials":"generic_oidc"));sync()}function sync(){const m2m=integration.value==="client_credentials";redirects.required=!m2m;redirects.disabled=m2m;redirects.placeholder=m2m?"Nie dotyczy Client Credentials":"https://xyz.example.com/oauth/callback";redirectHint.textContent=m2m?"Machine-to-Machine nie używa Redirect URI.":"Wildcardy są zabronione. Wymagany jest HTTPS, z wyjątkiem localhost do developmentu.";scope.value=m2m?"roles":"openid profile email roles";hint.textContent=integration.value==="public_pkce"?"Public Client bez sekretu; PKCE S256 jest obowiązkowe.":(m2m?"Confidential Client z grantem Client Credentials.":"Confidential Client z Authorization Code.")}next.onclick=()=>{if(s<5)s++;show()};prev.onclick=()=>{if(s>1)s--;show()};type.onchange=preset;integration.onchange=sync;preset();show();</script>';
Web::page('Dodaj aplikację', $content, $admin);
