<?php
declare(strict_types=1);
namespace ImAuthenticator;
final class DeliveryService
{
    public function __construct(private Database $db,private CryptoService $crypto,private SystemSettingsService $settings,private MailQueueService $mail,private AuditLog $audit){}

    public function createWebhook(string $url,array $events,int $actorUserId):array
    {
        $this->assertOutboundUrl($url);$events=array_values(array_unique(array_filter(array_map('strval',$events))));if($events===[])$events=['*'];$secret='imwh_'.Security::randomToken(32);$this->db->execute('INSERT INTO webhooks(url,secret_hash,secret_encrypted,events_json,enabled) VALUES(?,?,?,?,1)',[$url,Security::secretHash($secret),$this->crypto->encrypt($secret),json_encode($events,JSON_THROW_ON_ERROR)]);$id=$this->db->lastInsertId();$this->audit->write('webhook.created','success',$actorUserId,null,null,null,['webhook_id'=>$id,'url'=>$url]);return ['id'=>$id,'secret'=>$secret];
    }

    public function dispatch(int $limit=100):array
    {
        $events=$this->db->all('SELECT * FROM event_outbox WHERE published_at IS NULL ORDER BY id LIMIT '.max(1,min(500,$limit)));$ok=0;$failed=0;
        foreach($events as $event){$hooks=$this->matchingWebhooks((string)$event['event_type']);$terminal=true;foreach($hooks as $hook){$last=$this->db->one('SELECT * FROM webhook_deliveries WHERE webhook_id=? AND event_outbox_id=? ORDER BY attempt DESC LIMIT 1',[(int)$hook['id'],(int)$event['id']]);if($last&&in_array($last['status'],['success','dead'],true))continue;if($last&&$last['next_attempt_at']&&strtotime((string)$last['next_attempt_at'])>time()){$terminal=false;continue;}$attempt=(int)($last['attempt']??0)+1;$result=$this->postWebhook($hook,$event);$status=$result['ok']?'success':($attempt>=5?'dead':'failure');$next=$result['ok']||$attempt>=5?null:date('Y-m-d H:i:s',time()+min(3600,60*(2**$attempt)));$this->db->execute('INSERT INTO webhook_deliveries(webhook_id,event_outbox_id,attempt,status,response_code,error_message,next_attempt_at,delivered_at) VALUES(?,?,?,?,?,?,?,?)',[(int)$hook['id'],(int)$event['id'],$attempt,$status,$result['code'],$result['error'],$next,$result['ok']?date('Y-m-d H:i:s'):null]);if($result['ok']){$ok++;$this->db->execute('UPDATE webhooks SET last_success_at=NOW() WHERE id=?',[(int)$hook['id']]);}else{$failed++;$this->db->execute('UPDATE webhooks SET last_failure_at=NOW() WHERE id=?',[(int)$hook['id']]);if($attempt<5)$terminal=false;}}
            $this->processAlerts($event);$this->sendSyslog($event);if($terminal)$this->db->execute('UPDATE event_outbox SET published_at=NOW() WHERE id=?',[(int)$event['id']]);}
        return ['events'=>count($events),'webhook_success'=>$ok,'webhook_failures'=>$failed];
    }

    private function matchingWebhooks(string $type):array{$out=[];foreach($this->db->all('SELECT * FROM webhooks WHERE enabled=1') as $h){$events=json_decode((string)$h['events_json'],true);if(is_array($events)&&(in_array('*',$events,true)||in_array($type,$events,true)))$out[]=$h;}return $out;}
    private function postWebhook(array $hook,array $event):array{$url=(string)$hook['url'];try{$this->assertOutboundUrl($url);}catch(\Throwable $e){return ['ok'=>false,'code'=>null,'error'=>$e->getMessage()];}if(!function_exists('curl_init'))return ['ok'=>false,'code'=>null,'error'=>'ext-curl_missing'];$body=json_encode(['id'=>$event['event_uuid'],'type'=>$event['event_type'],'created_at'=>$event['created_at'],'data'=>json_decode((string)$event['payload_json'],true)],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$headers=['Content-Type: application/json','User-Agent: imAuthenticator/1','X-imAuthenticator-Event: '.$event['event_type'],'X-imAuthenticator-Delivery: '.$event['event_uuid']];if(!empty($hook['secret_encrypted'])){try{$secret=$this->crypto->decrypt((string)$hook['secret_encrypted']);$headers[]='X-imAuthenticator-Signature: sha256='.hash_hmac('sha256',$body,$secret);}catch(\Throwable){}}$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$body,CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>3,CURLOPT_TIMEOUT=>8,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS]);curl_exec($ch);$err=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);return ['ok'=>$err===''&&$code>=200&&$code<300,'code'=>$code?:null,'error'=>$err!==''?$err:($code>=200&&$code<300?null:'http_'.$code)];}
    private function processAlerts(array $event):void{$payload=json_decode((string)$event['payload_json'],true);$severity=(string)($payload['severity']??'warning');$rank=['info'=>0,'warning'=>1,'high'=>2,'critical'=>3];foreach($this->db->all('SELECT * FROM alert_rules WHERE enabled=1 AND (event_type=? OR event_type=\'*\')',[(string)$event['event_type']]) as $rule){if(($rank[$severity]??1)<($rank[$rule['minimum_severity']]??1))continue;if($this->db->one('SELECT 1 FROM alert_deliveries WHERE alert_rule_id=? AND event_outbox_id=?',[(int)$rule['id'],(int)$event['id']]))continue;$ok=true;$err=null;try{if(in_array($rule['channel'],['email','both'],true))$this->mail->queue((string)$rule['destination'],'imAuthenticator alert: '.$event['event_type'],json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),'security_alert');if(in_array($rule['channel'],['webhook','both'],true)){$tmp=['id'=>0,'url'=>$rule['destination'],'secret_encrypted'=>null];$r=$this->postWebhook($tmp,$event);$ok=$ok&&$r['ok'];$err=$r['error'];}}catch(\Throwable $e){$ok=false;$err=$e->getMessage();}$this->db->execute('INSERT INTO alert_deliveries(alert_rule_id,event_outbox_id,status,error_message) VALUES(?,?,?,?)',[(int)$rule['id'],(int)$event['id'],$ok?'success':'failure',$err]);}}
    private function sendSyslog(array $event):void{$msg='<134>1 '.gmdate('c').' imAuthenticator - - - ['.$event['event_type'].'] '.str_replace(["\r","\n"],' ',(string)$event['payload_json']);foreach($this->db->all('SELECT * FROM syslog_targets WHERE enabled=1') as $t){$scheme=$t['transport']==='udp'?'udp':($t['transport']==='tls'?'tls':'tcp');$errno=0;$err='';$fp=@stream_socket_client($scheme.'://'.$t['host'].':'.(int)$t['port'],$errno,$err,2,STREAM_CLIENT_CONNECT);if($fp){fwrite($fp,$msg."\n");fclose($fp);}}}
    private function assertOutboundUrl(string $url):void{$p=parse_url($url);if(!is_array($p)||strtolower((string)($p['scheme']??''))!=='https'||empty($p['host'])||isset($p['user'])||isset($p['pass']))throw new \RuntimeException('https_webhook_required');$host=(string)$p['host'];if((bool)$this->settings->get('allow_private_webhook_targets',false))return;$ips=@gethostbynamel($host)?:[];foreach($ips as $ip){if(filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE)===false)throw new \RuntimeException('private_webhook_target_blocked');}}
}
