<?php
declare(strict_types=1);
namespace ImAuthenticator;
final class DeviceRiskService
{
 public function __construct(private Database$db){}
 public function assess(int$userId,array$context):array{$score=0;$reasons=[];$deviceId=(int)($context['device_id']??0);if(($context['new_device']??false)||$deviceId<1||!$this->db->one('SELECT 1 FROM user_devices WHERE id=? AND user_id=? AND revoked_at IS NULL',[$deviceId,$userId])){$score+=30;$reasons[]='new_device';}$ip=(string)($context['ip']??Security::currentIp());$last=$this->db->one("SELECT ip_address,country_code,latitude,longitude,created_at FROM login_events WHERE user_id=? AND event_type='login_success' ORDER BY created_at DESC LIMIT 1",[$userId]);if($last&&$ip!==''&&$last['ip_address']!==$ip){$score+=15;$reasons[]='new_ip';}if($last&&!empty($context['country_code'])&&!empty($last['country_code'])&&strtoupper((string)$context['country_code'])!==strtoupper((string)$last['country_code'])&&time()-strtotime((string)$last['created_at'])<3600){$score+=35;$reasons[]='rapid_country_change';}if($last&&isset($context['latitude'],$context['longitude'])&&$last['latitude']!==null&&$last['longitude']!==null){$seconds=max(1,time()-strtotime((string)$last['created_at']));$km=$this->distanceKm((float)$last['latitude'],(float)$last['longitude'],(float)$context['latitude'],(float)$context['longitude']);if($seconds<43200&&$km>500&&$km/($seconds/3600)>1000){$score+=50;$reasons[]='impossible_travel';}}$f=$this->db->one("SELECT COUNT(*) AS c FROM login_events WHERE user_id=? AND event_type='login_failure' AND created_at>DATE_SUB(NOW(),INTERVAL 15 MINUTE)",[$userId]);$fails=min(5,(int)($f['c']??0));if($fails>0){$score+=$fails*5;$reasons[]='recent_failures';}return['score'=>min(100,$score),'reasons'=>array_values(array_unique($reasons))];}
 public function record(int$userId,?int$appId,string$type,array$context,int$score=0,array$reasons=[]):void{if(!in_array($type,['login_success','login_failure','mfa_success','mfa_failure','step_up','risk_denied','logout'],true))return;$this->db->execute('INSERT INTO login_events(user_id,application_id,event_type,ip_address,country_code,latitude,longitude,device_id,risk_score,risk_reasons_json) VALUES(?,?,?,?,?,?,?,?,?,?)',[$userId,$appId,$type,(string)($context['ip']??Security::currentIp()),$context['country_code']??null,$context['latitude']??null,$context['longitude']??null,($context['device_id']??0)>0?$context['device_id']:null,$score,$reasons===[]?null:json_encode($reasons,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);}
 private function distanceKm(float$a,float$b,float$c,float$d):float{$r=6371.0;$dLat=deg2rad($c-$a);$dLon=deg2rad($d-$b);$x=sin($dLat/2)**2+cos(deg2rad($a))*cos(deg2rad($c))*sin($dLon/2)**2;return$r*2*atan2(sqrt($x),sqrt(1-$x));}
}
