<?php
declare(strict_types=1);
namespace ImAuthenticator;
final class ExternalIdentityService
{
    public function __construct(private Database $db,private SystemSettingsService $settings,private AuditLog $audit,private array $config){}
    public function providers():array{if($this->settings->externalLoginEmergencyDisabled())return[];return $this->db->all("SELECT id,name,provider_type,config_json FROM identity_providers WHERE enabled=1 AND provider_type IN ('oidc','entra','google','github') ORDER BY name");}
    public function begin(int $providerId,string $returnPath='/dashboard'):string{$p=$this->provider($providerId);if($this->settings->externalLoginEmergencyDisabled())throw new \RuntimeException('external_login_disabled');if(!str_starts_with($returnPath,'/')||str_starts_with($returnPath,'//'))$returnPath='/dashboard';$cfg=$this->providerConfig($p);$end=$this->endpoints($p,$cfg);$state=Security::randomToken(32);$verifier=Security::randomToken(48);$challenge=rtrim(strtr(base64_encode(hash('sha256',$verifier,true)),'+/','-_'),'=');$nonce=Security::randomToken(24);$this->db->execute('INSERT INTO external_auth_states(identity_provider_id,state_hash,code_verifier,nonce,return_path,expires_at) VALUES(?,?,?,?,?,DATE_ADD(NOW(),INTERVAL 10 MINUTE))',[$providerId,Security::tokenHash($state),$verifier,$p['provider_type']==='github'?null:$nonce,$returnPath]);$params=['client_id'=>(string)$cfg['client_id'],'redirect_uri'=>rtrim((string)$this->config['issuer'],'/').'/auth/external/callback','response_type'=>'code','scope'=>(string)($cfg['scopes']??($p['provider_type']==='github'?'read:user user:email':'openid profile email')),'state'=>$state,'code_challenge'=>$challenge,'code_challenge_method'=>'S256'];if($p['provider_type']!=='github')$params['nonce']=$nonce;return $end['authorization_endpoint'].'?'.http_build_query($params);}
    public function callback(string $state,string $code):array{return $this->db->transaction(function()use($state,$code):array{$s=$this->db->one('SELECT * FROM external_auth_states WHERE state_hash=? FOR UPDATE',[Security::tokenHash($state)]);if(!$s||$s['used_at']!==null||strtotime((string)$s['expires_at'])<=time())throw new \RuntimeException('invalid_state');$p=$this->provider((int)$s['identity_provider_id']);$cfg=$this->providerConfig($p);$end=$this->endpoints($p,$cfg);$token=$this->postForm($end['token_endpoint'],['grant_type'=>'authorization_code','code'=>$code,'redirect_uri'=>rtrim((string)$this->config['issuer'],'/').'/auth/external/callback','client_id'=>(string)$cfg['client_id'],'client_secret'=>$this->clientSecret($cfg),'code_verifier'=>(string)$s['code_verifier']]);$profile=$p['provider_type']==='github'?$this->githubProfile((string)($token['access_token']??'')):$this->oidcProfile($p,$cfg,$end,$token,(string)$s['nonce']);$userId=$this->resolveUser($p,$cfg,$profile);$this->db->execute('UPDATE external_auth_states SET used_at=NOW() WHERE id=?',[(int)$s['id']]);$this->audit->write('external_login.success','success',$userId,$userId,null,null,['provider_id'=>(int)$p['id'],'type'=>$p['provider_type']]);return ['user_id'=>$userId,'return_path'=>(string)$s['return_path'],'auth_level'=>max(1,min(3,(int)($cfg['auth_level']??1)))];});}
    private function provider(int $id):array{$p=$this->db->one('SELECT * FROM identity_providers WHERE id=? AND enabled=1',[$id]);if(!$p)throw new \RuntimeException('provider_not_found');return$p;}
    private function providerConfig(array $p):array{$c=json_decode((string)$p['config_json'],true);if(!is_array($c)||empty($c['client_id']))throw new \RuntimeException('provider_not_configured');return$c;}
    private function endpoints(array $p,array $cfg):array{if($p['provider_type']==='github')return['authorization_endpoint'=>'https://github.com/login/oauth/authorize','token_endpoint'=>'https://github.com/login/oauth/access_token','userinfo_endpoint'=>'https://api.github.com/user'];$issuer=(string)($cfg['issuer']??'');if($p['provider_type']==='google'&&$issuer==='')$issuer='https://accounts.google.com';if($p['provider_type']==='entra'&&$issuer==='')$issuer='https://login.microsoftonline.com/'.rawurlencode((string)($cfg['tenant']??'common')).'/v2.0';$discovery=$this->getJson(rtrim($issuer,'/').'/.well-known/openid-configuration');foreach(['authorization_endpoint','token_endpoint','jwks_uri'] as $k)if(empty($discovery[$k]))throw new \RuntimeException('invalid_discovery');$discovery['issuer']=$discovery['issuer']??$issuer;return$discovery;}
    private function clientSecret(array $cfg):string{$env=(string)($cfg['client_secret_env']??'');return$env!==''?(string)(getenv($env)?:''):(string)($cfg['client_secret']??'');}
    private function oidcProfile(array $p,array $cfg,array $end,array $token,string $nonce):array{$jwt=(string)($token['id_token']??'');if($jwt==='')throw new \RuntimeException('id_token_missing');$claims=$this->verifyRs256Jwt($jwt,(string)$end['jwks_uri'],(string)$end['issuer'],(string)$cfg['client_id'],$nonce);return['sub'=>(string)$claims['sub'],'email'=>strtolower((string)($claims['email']??$claims['preferred_username']??'')),'name'=>(string)($claims['name']??$claims['preferred_username']??'External user'),'username'=>(string)($claims['preferred_username']??''),'claims'=>$claims];}
    private function githubProfile(string $access):array{if($access==='')throw new \RuntimeException('access_token_missing');$u=$this->getJson('https://api.github.com/user',$access);$emails=$this->getJson('https://api.github.com/user/emails',$access);$email='';if(is_array($emails))foreach($emails as $e)if(is_array($e)&&($e['primary']??false)&&($e['verified']??false)){$email=strtolower((string)$e['email']);break;}return['sub'=>(string)($u['id']??''),'email'=>$email,'name'=>(string)($u['name']??$u['login']??'GitHub user'),'username'=>(string)($u['login']??''),'claims'=>$u];}
    private function resolveUser(array $p,array $cfg,array $profile):int{$subject=(string)$profile['sub'];if($subject==='')throw new \RuntimeException('subject_missing');$ext=$this->db->one('SELECT user_id FROM external_identities WHERE identity_provider_id=? AND external_subject=?',[(int)$p['id'],$subject]);if($ext)return(int)$ext['user_id'];$email=strtolower((string)$profile['email']);$user=$email!==''?$this->db->one('SELECT DISTINCT u.id FROM users u LEFT JOIN user_emails ue ON ue.user_id=u.id WHERE LOWER(u.email)=? OR (LOWER(ue.email)=? AND ue.verified_at IS NOT NULL) LIMIT 1',[$email,$email]):null;if(!$user){if(!(bool)($cfg['auto_provision']??false))throw new \RuntimeException('provisioning_not_allowed');$allowed=$cfg['allowed_domains']??[];if(is_array($allowed)&&$allowed!==[]){$domain=strtolower(substr(strrchr($email,'@')?:'',1));if(!in_array($domain,array_map('strtolower',$allowed),true))throw new \RuntimeException('email_domain_not_allowed');}if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new \RuntimeException('verified_email_required');$this->db->execute("INSERT INTO users(uuid,name,username,email,password_hash,enabled,lifecycle_status) VALUES(?,?,?,?,?,1,'active')",[Security::uuidV4(),(string)$profile['name'],($profile['username']?:null),$email,password_hash(Security::randomToken(48),PASSWORD_ARGON2ID)]);$uid=$this->db->lastInsertId();$this->db->execute('INSERT IGNORE INTO user_emails(user_id,email,is_primary,verified_at) VALUES(?,?,1,NOW())',[$uid,$email]);}else$uid=(int)$user['id'];$this->db->execute('INSERT INTO external_identities(user_id,identity_provider_id,external_subject,external_username,profile_json,last_login_at) VALUES(?,?,?,?,?,NOW())',[$uid,(int)$p['id'],$subject,(string)$profile['username'],json_encode($profile['claims'],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)]);return$uid;}
    private function postForm(string $url,array $data):array{if(!function_exists('curl_init'))throw new \RuntimeException('ext_curl_required');$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($data),CURLOPT_HTTPHEADER=>['Accept: application/json','User-Agent: imAuthenticator/1'],CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS]);$raw=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if(!is_string($raw)||$err!==''||$code<200||$code>=300)throw new \RuntimeException('external_token_exchange_failed');$j=json_decode($raw,true);if(!is_array($j))parse_str($raw,$j);if(!is_array($j))throw new \RuntimeException('invalid_external_response');return$j;}
    private function getJson(string $url,?string $bearer=null):array{if(!function_exists('curl_init'))throw new \RuntimeException('ext_curl_required');$headers=['Accept: application/json','User-Agent: imAuthenticator/1'];if($bearer)$headers[]='Authorization: Bearer '.$bearer;$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS]);$raw=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if(!is_string($raw)||$code<200||$code>=300)throw new \RuntimeException('external_http_failed');$j=json_decode($raw,true);if(!is_array($j))throw new \RuntimeException('invalid_external_json');return$j;}
    private function verifyRs256Jwt(string $jwt,string $jwksUri,string $issuer,string $audience,string $nonce):array{$parts=explode('.',$jwt);if(count($parts)!==3)throw new \RuntimeException('invalid_id_token');$header=json_decode($this->b64d($parts[0]),true);$claims=json_decode($this->b64d($parts[1]),true);if(!is_array($header)||!is_array($claims)||($header['alg']??'')!=='RS256')throw new \RuntimeException('unsupported_id_token');$jwks=$this->getJson($jwksUri);$key=null;foreach(($jwks['keys']??[]) as $jwk)if(is_array($jwk)&&($jwk['kid']??null)===($header['kid']??null)){$key=$jwk;break;}if(!$key)throw new \RuntimeException('jwks_key_not_found');$pem=$this->rsaPem($key);$sig=$this->b64d($parts[2]);if(openssl_verify($parts[0].'.'.$parts[1],$sig,$pem,OPENSSL_ALGO_SHA256)!==1)throw new \RuntimeException('invalid_id_token_signature');if(($claims['iss']??'')!==$issuer||!$this->audMatches($claims['aud']??null,$audience)||(int)($claims['exp']??0)<=time()-30||($claims['nonce']??'')!==$nonce)throw new \RuntimeException('invalid_id_token_claims');return$claims;}
    private function audMatches(mixed $aud,string $expected):bool{return is_string($aud)?hash_equals($expected,$aud):(is_array($aud)&&in_array($expected,$aud,true));}
    private function rsaPem(array $jwk):string{$n=$this->b64d((string)($jwk['n']??''));$e=$this->b64d((string)($jwk['e']??''));if($n===''||$e==='')throw new \RuntimeException('invalid_jwk');$len=function(int $l):string{return$l<128?chr($l):chr(0x80+strlen($b=ltrim(pack('N',$l),"\0"))).$b;};$int=function(string $v)use($len):string{if((ord($v[0])&0x80)!==0)$v="\0".$v;return"\x02".$len(strlen($v)).$v;};$seq=$int($n).$int($e);$rsa="\x30".$len(strlen($seq)).$seq;$alg="\x30\x0d\x06\x09\x2a\x86\x48\x86\xf7\x0d\x01\x01\x01\x05\x00";$bit="\x03".$len(strlen($rsa)+1)."\0".$rsa;$spki="\x30".$len(strlen($alg.$bit)).$alg.$bit;return"-----BEGIN PUBLIC KEY-----\n".chunk_split(base64_encode($spki),64,"\n")."-----END PUBLIC KEY-----\n";}
    private function b64d(string $v):string{$p=strtr($v,'-_','+/');$p.=str_repeat('=',(4-strlen($p)%4)%4);return(string)base64_decode($p,true);}
}
