<?php
declare(strict_types=1);
namespace ImAuthenticator;

use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\Image\SvgImageBackEnd;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;

final class IntegrationToolkitService
{
    public function __construct(private Database$db,private array$config,private ApplicationAccessService$access,private ConditionalAccessService$conditional){}
    public function templates():array{return$this->db->all('SELECT * FROM application_templates WHERE enabled=1 ORDER BY name');}
    public function snippets(array$app):array{$issuer=rtrim((string)$this->config['issuer'],'/');$client=(string)$app['client_id'];$redirect=$this->db->one('SELECT redirect_uri FROM application_redirect_uris WHERE application_id=? ORDER BY id LIMIT 1',[(int)$app['id']])['redirect_uri']??'';return['php'=>"// OIDC client\n\$issuer = '".$issuer."';\n\$clientId = '".$client."';\n\$redirectUri = '".$redirect."';",'python'=>"ISSUER = '".$issuer."'\nCLIENT_ID = '".$client."'\nREDIRECT_URI = '".$redirect."'",'node'=>"const issuer = '".$issuer."';\nconst clientId = '".$client."';\nconst redirectUri = '".$redirect."';",'nginx'=>"location /oauth/callback {\n    proxy_set_header X-Forwarded-Proto https;\n    proxy_pass http://app;\n}",'apache'=>"RewriteEngine On\n# Callback: ".$redirect];}
    public function configurationPayload(array$app):array{$issuer=rtrim((string)$this->config['issuer'],'/');$redirects=array_column($this->db->all('SELECT redirect_uri FROM application_redirect_uris WHERE application_id=? ORDER BY id',[(int)$app['id']]),'redirect_uri');return['issuer'=>$issuer,'client_id'=>$app['client_id'],'discovery'=>$issuer.'/.well-known/openid-configuration','authorization_endpoint'=>$issuer.'/oauth/authorize','token_endpoint'=>$issuer.'/oauth/token','userinfo_endpoint'=>$issuer.'/oauth/userinfo','redirect_uris'=>$redirects,'client_type'=>$app['client_type']];}
    public function qrSvg(array$app):string{$payload='imauthenticator://configure?'.http_build_query(['issuer'=>rtrim((string)$this->config['issuer'],'/'),'client_id'=>(string)$app['client_id'],'redirect_uri'=>(string)($this->db->one('SELECT redirect_uri FROM application_redirect_uris WHERE application_id=? ORDER BY id LIMIT 1',[(int)$app['id']])['redirect_uri']??'')]);$renderer=new ImageRenderer(new RendererStyle(260,8),new SvgImageBackEnd());return(new Writer($renderer))->writeString($payload);}
    public function testUser(int$appId,int$userId,array$context):array{$app=$this->db->one('SELECT * FROM applications WHERE id=? AND deleted_at IS NULL',[$appId]);$user=$this->db->one('SELECT id,uuid,name,username,email,enabled,lifecycle_status FROM users WHERE id=?',[$userId]);if(!$app||!$user)throw new \RuntimeException('not_found');$ctx=['auth_level'=>max(1,min(3,(int)($context['auth_level']??1))),'auth_time'=>time(),'risk_score'=>max(0,min(100,(int)($context['risk_score']??0))),'country_code'=>strtoupper(substr((string)($context['country_code']??''),0,2)),'ip'=>(string)($context['ip']??'198.51.100.10'),'device_id'=>(int)($context['device_id']??0)];$entitled=$this->access->hasAccess($userId,$app,$ctx);$decision=$entitled?$this->conditional->evaluate($userId,$app,$ctx):['allowed'=>false,'action'=>'deny','reasons'=>['no_application_entitlement']];return['user'=>['id'=>$userId,'name'=>$user['name'],'email'=>$user['email'],'lifecycle_status'=>$user['lifecycle_status']],'application'=>['id'=>$appId,'name'=>$app['name'],'access_policy'=>$app['access_policy']],'entitled'=>$entitled,'conditional_access'=>$decision,'context'=>$ctx,'roles'=>$this->access->rolesForUser($userId,$appId),'claims'=>$this->previewClaims($app,$user)];}
    public function runDiagnostics(int$applicationId,?int$actorUserId=null):int{$app=$this->db->one('SELECT * FROM applications WHERE id=? AND deleted_at IS NULL',[$applicationId]);if(!$app)throw new \RuntimeException('not_found');$this->db->execute('INSERT INTO integration_diagnostic_runs(application_id,started_by) VALUES(?,?)',[$applicationId,$actorUserId]);$run=$this->db->lastInsertId();$checks=[];$checks[]=['client_enabled',(bool)$app['enabled']?'success':'failure',(bool)$app['enabled']?'Klient aktywny':'Klient wyłączony'];$redirects=$this->db->all('SELECT redirect_uri FROM application_redirect_uris WHERE application_id=?',[$applicationId]);$checks[]=['redirect_uri',$app['integration_type']==='client_credentials'||$redirects!==[]?'success':'failure','Redirect URI: '.count($redirects)];$checks[]=['discovery','success',rtrim((string)$this->config['issuer'],'/').'/.well-known/openid-configuration'];$hasSecret=!empty($app['client_secret_hash'])||$this->db->one('SELECT 1 FROM client_secrets WHERE application_id=? AND revoked_at IS NULL AND valid_from<=NOW() AND (valid_until IS NULL OR valid_until>NOW())',[$applicationId]);$checks[]=['client_secret',$app['client_type']==='public'||$hasSecret?'success':'failure',$app['client_type']==='public'?'Public client':'Confidential client'];$status='success';foreach($checks as[$name,$s,$detail]){$this->db->execute('INSERT INTO integration_diagnostic_checks(run_id,check_name,status,detail) VALUES(?,?,?,?)',[$run,$name,$s,$detail]);if($s==='failure')$status='failure';}$this->db->execute('UPDATE integration_diagnostic_runs SET status=?,finished_at=NOW() WHERE id=?',[$status,$run]);return$run;}
    private function previewClaims(array$app,array$user):array{$roles=$this->access->rolesForUser((int)$user['id'],(int)$app['id']);$mappings=$this->db->all('SELECT * FROM claims_mappings WHERE application_id=? ORDER BY id',[(int)$app['id']]);if($mappings===[])return['id_token'=>['sub'=>$user['uuid'],'name'=>$user['name'],'email'=>$user['email'],'roles'=>$roles],'userinfo'=>['sub'=>$user['uuid'],'name'=>$user['name'],'email'=>$user['email'],'roles'=>$roles]];$id=['sub'=>$user['uuid']];$ui=['sub'=>$user['uuid']];foreach($mappings as$m){$value=null;if($m['source_type']==='standard')$value=$user[(string)$m['source_key']]??null;elseif($m['source_type']==='role')$value=$roles;elseif($m['source_type']==='static')$value=$m['static_value'];elseif($m['source_type']==='attribute'){$a=$this->db->one('SELECT attribute_value FROM user_attributes WHERE user_id=? AND attribute_key=?',[(int)$user['id'],(string)$m['source_key']]);$value=$a['attribute_value']??null;}if($value===null)continue;if((bool)$m['include_in_id_token'])$id[(string)$m['claim_name']]=$value;if((bool)$m['include_in_userinfo'])$ui[(string)$m['claim_name']]=$value;}return['id_token'=>$id,'userinfo'=>$ui];}
}
