<?php
declare(strict_types=1);
namespace ImAuthenticator;
final class MfaService
{
    public function __construct(private Database $db,private CryptoService $crypto,private AuditLog $audit,private array $config){}
    public function beginTotp(int $userId,string $label='Authenticator'):array{$user=$this->db->one('SELECT email FROM users WHERE id=? AND enabled=1',[$userId]);if(!$user)throw new \RuntimeException('user_not_found');$secret=$this->base32Encode(random_bytes(20));$this->db->execute("DELETE FROM mfa_methods WHERE user_id=? AND method='totp' AND enabled=0",[$userId]);$this->db->execute("INSERT INTO mfa_methods(user_id,method,label,secret_encrypted,enabled) VALUES(?,'totp',?,?,0)",[$userId,$label,$this->crypto->encrypt($secret)]);$id=$this->db->lastInsertId();$issuer=(string)(parse_url((string)$this->config['issuer'],PHP_URL_HOST)?:'imAuthenticator');$uri='otpauth://totp/'.rawurlencode($issuer.':'.$user['email']).'?'.http_build_query(['secret'=>$secret,'issuer'=>$issuer,'algorithm'=>'SHA1','digits'=>6,'period'=>30]);return['method_id'=>$id,'secret'=>$secret,'otpauth_uri'=>$uri];}
    public function confirmTotp(int $userId,int $methodId,string $code):void{$row=$this->db->one("SELECT * FROM mfa_methods WHERE id=? AND user_id=? AND method='totp' AND enabled=0",[$methodId,$userId]);if(!$row||!$this->verifyTotpSecret($this->crypto->decrypt((string)$row['secret_encrypted']),$code))throw new \RuntimeException('invalid_totp');$this->db->execute('UPDATE mfa_methods SET enabled=1,last_used_at=NOW() WHERE id=?',[$methodId]);$this->audit->write('mfa.totp.enrolled','success',$userId,$userId,null,null,['method_id'=>$methodId]);}
    public function verify(int $userId,string $code):bool{$code=preg_replace('/\s+/','',$code)??'';foreach($this->db->all("SELECT * FROM mfa_methods WHERE user_id=? AND method='totp' AND enabled=1",[$userId]) as $m){try{if($this->verifyTotpSecret($this->crypto->decrypt((string)$m['secret_encrypted']),$code)){$this->db->execute('UPDATE mfa_methods SET last_used_at=NOW() WHERE id=?',[(int)$m['id']]);$this->audit->write('mfa.totp.success','success',$userId,$userId);return true;}}catch(\Throwable){}}if($this->consumeBackupCode($userId,$code)){$this->audit->write('mfa.backup_code.success','success',$userId,$userId);return true;}$this->audit->write('mfa.verification.failed','denied',$userId,$userId);return false;}
    public function regenerateBackupCodes(int $userId):array{$this->db->execute('DELETE FROM backup_codes WHERE user_id=? AND used_at IS NULL',[$userId]);$codes=[];for($i=0;$i<10;$i++){$raw=strtoupper(substr(bin2hex(random_bytes(5)),0,5).'-'.substr(bin2hex(random_bytes(5)),0,5));$codes[]=$raw;$this->db->execute('INSERT INTO backup_codes(user_id,code_hash) VALUES(?,?)',[$userId,password_hash($raw,PASSWORD_ARGON2ID)]);} $this->audit->write('mfa.backup_codes.regenerated','success',$userId,$userId,null,null,['count'=>count($codes)]);return$codes;}
    public function methods(int $userId):array{return$this->db->all('SELECT id,method,label,enabled,created_at,last_used_at FROM mfa_methods WHERE user_id=? ORDER BY created_at DESC',[$userId]);}
    public function remainingBackupCodes(int $userId):int{$r=$this->db->one('SELECT COUNT(*) AS c FROM backup_codes WHERE user_id=? AND used_at IS NULL',[$userId]);return(int)($r['c']??0);}
    private function consumeBackupCode(int $userId,string $code):bool{foreach($this->db->all('SELECT id,code_hash FROM backup_codes WHERE user_id=? AND used_at IS NULL',[$userId]) as $r)if(password_verify(strtoupper($code),(string)$r['code_hash'])){$this->db->execute('UPDATE backup_codes SET used_at=NOW() WHERE id=? AND used_at IS NULL',[(int)$r['id']]);return true;}return false;}
    private function verifyTotpSecret(string $secret,string $code):bool{if(!preg_match('/^\d{6}$/',$code))return false;$key=$this->base32Decode($secret);$counter=intdiv(time(),30);for($offset=-1;$offset<=1;$offset++){if(hash_equals($this->hotp($key,$counter+$offset),$code))return true;}return false;}
    private function hotp(string $key,int $counter):string{$binary=pack('N2',($counter>>32)&0xffffffff,$counter&0xffffffff);$h=hash_hmac('sha1',$binary,$key,true);$o=ord($h[19])&0x0f;$n=((ord($h[$o])&0x7f)<<24)|((ord($h[$o+1])&0xff)<<16)|((ord($h[$o+2])&0xff)<<8)|(ord($h[$o+3])&0xff);return str_pad((string)($n%1000000),6,'0',STR_PAD_LEFT);}
    private function base32Encode(string $data):string{$alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';foreach(str_split($data) as $c)$bits.=str_pad(decbin(ord($c)),8,'0',STR_PAD_LEFT);$out='';foreach(str_split($bits,5) as $chunk){$chunk=str_pad($chunk,5,'0',STR_PAD_RIGHT);$out.=$alphabet[bindec($chunk)];}return$out;}
    private function base32Decode(string $s):string{$alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';foreach(str_split(strtoupper($s)) as $c){$p=strpos($alphabet,$c);if($p===false)continue;$bits.=str_pad(decbin($p),5,'0',STR_PAD_LEFT);}$out='';foreach(str_split($bits,8) as $chunk)if(strlen($chunk)===8)$out.=chr(bindec($chunk));return$out;}
}
