<?php
declare(strict_types=1);
namespace ImAuthenticator;
final class OAuthSecurityService
{
    public function __construct(private Database $db,private ApplicationAccessService $access,private AuditLog $audit){}
    public function tokenExchange(array $input,?string $authorizationHeader):array{$target=$this->authenticateClient($input,$authorizationHeader);$sec=$this->db->one('SELECT token_exchange_enabled FROM application_oauth_security WHERE application_id=?',[(int)$target['id']]);if(!$sec||(bool)$sec['token_exchange_enabled']!==true)throw new \RuntimeException('unauthorized_client');if((string)($input['subject_token_type']??'')!=='urn:ietf:params:oauth:token-type:access_token')throw new \RuntimeException('invalid_request');$subject=(string)($input['subject_token']??'');$row=$this->db->one('SELECT * FROM oauth_access_tokens WHERE token_hash=? AND revoked_at IS NULL AND expires_at>NOW()',[Security::tokenHash($subject)]);if(!$row||!$row['user_id'])throw new \RuntimeException('invalid_grant');$policy=$this->db->one('SELECT * FROM token_exchange_policies WHERE source_application_id=? AND target_application_id=? AND enabled=1',[(int)$row['application_id'],(int)$target['id']]);if(!$policy)throw new \RuntimeException('access_denied');$uid=(int)$row['user_id'];if(!$this->access->hasAccess($uid,$target))throw new \RuntimeException('access_denied');$allowed=json_decode((string)$policy['allowed_scopes_json'],true);if(!is_array($allowed))$allowed=[];$requested=array_values(array_unique(array_filter(preg_split('/\s+/',trim((string)($input['scope']??implode(' ',$allowed))))?:[])));if(array_diff($requested,$allowed)!==[])throw new \RuntimeException('invalid_scope');$token=Security::randomToken(48);$this->db->execute('INSERT INTO oauth_access_tokens(token_hash,application_id,user_id,scopes,expires_at) VALUES(?,?,?,?,DATE_ADD(NOW(),INTERVAL 1 HOUR))',[Security::tokenHash($token),(int)$target['id'],$uid,implode(' ',$requested)]);$this->audit->write('oauth.token_exchange.success','success',$uid,$uid,(int)$target['id'],null,['source_application_id'=>(int)$row['application_id']]);return['access_token'=>$token,'issued_token_type'=>'urn:ietf:params:oauth:token-type:access_token','token_type'=>'Bearer','expires_in'=>3600,'scope'=>implode(' ',$requested)];}
    private function authenticateClient(array $input,?string $header):array{$id=(string)($input['client_id']??'');$secret=(string)($input['client_secret']??'');if($header&&str_starts_with($header,'Basic ')){$d=base64_decode(substr($header,6),true);if(is_string($d)&&str_contains($d,':')){[$id,$secret]=explode(':',$d,2);$id=rawurldecode($id);$secret=rawurldecode($secret);}}$app=$this->db->one("SELECT * FROM applications WHERE client_id=? AND client_type='confidential' AND enabled=1 AND deleted_at IS NULL",[$id]);if(!$app)throw new \RuntimeException('invalid_client');$ok=Security::verifySecret($secret,$app['client_secret_hash']);if(!$ok)foreach($this->db->all('SELECT secret_hash FROM client_secrets WHERE application_id=? AND revoked_at IS NULL AND valid_from<=NOW() AND (valid_until IS NULL OR valid_until>NOW())',[(int)$app['id']]) as $s)if(Security::verifySecret($secret,(string)$s['secret_hash'])){$ok=true;break;}if(!$ok)throw new \RuntimeException('invalid_client');return$app;}
}
