<?php
declare(strict_types=1);
namespace ImAuthenticator;
final class ScimOutboundService
{
    public function __construct(private Database $db,private CryptoService $crypto,private ApplicationAccessService $access,private AuditLog $audit){}
    public function createConnector(int $applicationId,string $baseUrl,string $bearer,int $actorUserId):int{$baseUrl=rtrim(trim($baseUrl),'/');$this->assertUrl($baseUrl);if($bearer==='')throw new \RuntimeException('bearer_required');$this->db->execute("INSERT INTO scim_connectors(application_id,enabled,base_url,direction,bearer_token_hash,bearer_token_encrypted,mapping_json) VALUES(?,1,?,'outbound',?,?,?)",[$applicationId,$baseUrl,Security::tokenHash($bearer),$this->crypto->encrypt($bearer),json_encode(['userName'=>'email','displayName'=>'name'],JSON_THROW_ON_ERROR)]);$id=$this->db->lastInsertId();$this->audit->write('scim.outbound.created','success',$actorUserId,null,$applicationId,null,['connector_id'=>$id]);return$id;}
    public function sync(int $connectorId,int $actorUserId):array{$c=$this->db->one("SELECT sc.*,a.name AS app_name FROM scim_connectors sc JOIN applications a ON a.id=sc.application_id WHERE sc.id=? AND sc.enabled=1 AND sc.direction='outbound' AND a.enabled=1 AND a.deleted_at IS NULL",[$connectorId]);if(!$c)throw new \RuntimeException('connector_not_found');$token=$this->crypto->decrypt((string)$c['bearer_token_encrypted']);$created=0;$updated=0;$disabled=0;$groups=0;$users=$this->db->all("SELECT u.id,u.uuid,u.name,u.email,u.username FROM application_users au JOIN users u ON u.id=au.user_id WHERE au.application_id=? AND au.enabled=1 AND au.revoked_at IS NULL AND (au.valid_from IS NULL OR au.valid_from<=NOW()) AND (au.valid_until IS NULL OR au.valid_until>NOW()) AND u.enabled=1 AND u.lifecycle_status='active'",[(int)$c['application_id']]);$activeIds=[];foreach($users as $u){$activeIds[]=(int)$u['id'];$rid=$this->resourceId((int)$u['id'],$connectorId);if(!$rid){$found=$this->searchUser($c,$token,(string)$u['email']);if($found)$rid=$found;if(!$rid){$r=$this->request($c,$token,'POST','/Users',['schemas'=>['urn:ietf:params:scim:schemas:core:2.0:User'],'externalId'=>$u['uuid'],'userName'=>$u['email'],'displayName'=>$u['name'],'active'=>true,'emails'=>[['value'=>$u['email'],'primary'=>true]]]);$rid=(string)($r['id']??'');if($rid==='')throw new \RuntimeException('scim_remote_id_missing');$created++;}$this->storeResourceId((int)$u['id'],$connectorId,$rid);}else{$this->request($c,$token,'PATCH','/Users/'.rawurlencode($rid),['schemas'=>['urn:ietf:params:scim:api:messages:2.0:PatchOp'],'Operations'=>[['op'=>'replace','path'=>'active','value'=>true],['op'=>'replace','path'=>'displayName','value'=>$u['name']],['op'=>'replace','path'=>'userName','value'=>$u['email']]]]);$updated++;}}
        $prefix='scim.out.'.$connectorId.'.resourceId';foreach($this->db->all('SELECT user_id,attribute_value FROM user_attributes WHERE attribute_key=?',[$prefix]) as $m){$uid=(int)$m['user_id'];if(in_array($uid,$activeIds,true))continue;$rid=(string)$m['attribute_value'];if($rid!==''){try{$this->request($c,$token,'PATCH','/Users/'.rawurlencode($rid),['schemas'=>['urn:ietf:params:scim:api:messages:2.0:PatchOp'],'Operations'=>[['op'=>'replace','path'=>'active','value'=>false]]]);$disabled++;}catch(\Throwable){}}}
        foreach($this->db->all('SELECT * FROM app_roles WHERE application_id=? ORDER BY id',[(int)$c['application_id']]) as $role){$members=[];foreach($this->db->all('SELECT u.id FROM app_user_roles aur JOIN users u ON u.id=aur.user_id WHERE aur.application_id=? AND aur.app_role_id=?',[(int)$c['application_id'],(int)$role['id']]) as $ru){$rid=$this->resourceId((int)$ru['id'],$connectorId);if($rid)$members[]=['value'=>$rid];}$mapping=$this->db->one('SELECT * FROM scim_group_mappings WHERE scim_connector_id=? AND app_role_id=?',[$connectorId,(int)$role['id']]);$gid=$mapping['external_group_id']??null;if(!$gid){$found=$this->searchGroup($c,$token,(string)$role['name']);if($found)$gid=$found;if(!$gid){$r=$this->request($c,$token,'POST','/Groups',['schemas'=>['urn:ietf:params:scim:schemas:core:2.0:Group'],'displayName'=>$role['name'],'members'=>$members]);$gid=(string)($r['id']??'');}if($gid!=='')$this->db->execute('INSERT INTO scim_group_mappings(scim_connector_id,app_role_id,external_group_id,display_name) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE external_group_id=VALUES(external_group_id),display_name=VALUES(display_name)',[$connectorId,(int)$role['id'],$gid,$role['name']]);}elseif($gid!=='')$this->request($c,$token,'PATCH','/Groups/'.rawurlencode((string)$gid),['schemas'=>['urn:ietf:params:scim:api:messages:2.0:PatchOp'],'Operations'=>[['op'=>'replace','path'=>'members','value'=>$members]]]);$groups++;}
        $this->db->execute('UPDATE scim_connectors SET last_sync_at=NOW() WHERE id=?',[$connectorId]);$result=['created'=>$created,'updated'=>$updated,'disabled'=>$disabled,'groups'=>$groups];$this->audit->write('scim.outbound.sync','success',$actorUserId,null,(int)$c['application_id'],null,['connector_id'=>$connectorId]+$result);return$result;}
    private function resourceId(int $userId,int $connectorId):?string{$r=$this->db->one('SELECT attribute_value FROM user_attributes WHERE user_id=? AND attribute_key=?',[$userId,'scim.out.'.$connectorId.'.resourceId']);return$r?(string)$r['attribute_value']:null;}
    private function storeResourceId(int $userId,int $connectorId,string $rid):void{$this->db->execute("INSERT INTO user_attributes(user_id,attribute_key,attribute_value,source) VALUES(?,?,?,'scim') ON DUPLICATE KEY UPDATE attribute_value=VALUES(attribute_value),source='scim'",[$userId,'scim.out.'.$connectorId.'.resourceId',$rid]);}
    private function searchUser(array $c,string $token,string $email):?string{$r=$this->request($c,$token,'GET','/Users?'.http_build_query(['filter'=>'userName eq "'.$email.'"','count'=>2]),null);$resources=$r['Resources']??[];return is_array($resources)&&isset($resources[0]['id'])?(string)$resources[0]['id']:null;}
    private function searchGroup(array $c,string $token,string $name):?string{$r=$this->request($c,$token,'GET','/Groups?'.http_build_query(['filter'=>'displayName eq "'.$name.'"','count'=>2]),null);$resources=$r['Resources']??[];return is_array($resources)&&isset($resources[0]['id'])?(string)$resources[0]['id']:null;}
    private function request(array $c,string $token,string $method,string $path,?array $payload):array{$base=rtrim((string)$c['base_url'],'/');$this->assertUrl($base);if(!function_exists('curl_init'))throw new \RuntimeException('ext_curl_required');$url=$base.$path;$headers=['Accept: application/scim+json','Content-Type: application/scim+json','Authorization: Bearer '.$token,'User-Agent: imAuthenticator/1'];$ch=curl_init($url);$opts=[CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>15,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS];if($payload!==null)$opts[CURLOPT_POSTFIELDS]=json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);curl_setopt_array($ch,$opts);$raw=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if($err!==''||$code<200||$code>=300)throw new \RuntimeException('scim_remote_error:'.($err!==''?$err:'http_'.$code));if($raw===''||$raw===false)return[];$json=json_decode((string)$raw,true);return is_array($json)?$json:[];}
    private function assertUrl(string $url):void{$p=parse_url($url);if(!is_array($p)||strtolower((string)($p['scheme']??''))!=='https'||empty($p['host'])||isset($p['user'])||isset($p['pass']))throw new \RuntimeException('scim_https_url_required');$ips=@gethostbynamel((string)$p['host'])?:[];foreach($ips as $ip)if(filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE)===false)throw new \RuntimeException('private_scim_target_blocked');}
}
