<?php
declare(strict_types=1);

namespace ImAuthenticator;

use RuntimeException;

final class UserMergeService
{
    public function __construct(private Database $db,private AuditLog $audit){}

    public function merge(int $sourceUserId,int $targetUserId,int $actorUserId,string $reason): void
    {
        if($sourceUserId<1||$targetUserId<1||$sourceUserId===$targetUserId)throw new RuntimeException('invalid_merge_users');$reason=trim($reason);if($reason==='')throw new RuntimeException('merge_reason_required');
        $source=$this->db->one('SELECT * FROM users WHERE id=?',[$sourceUserId]);$target=$this->db->one('SELECT * FROM users WHERE id=?',[$targetUserId]);if(!$source||!$target)throw new RuntimeException('user_not_found');if((bool)$source['is_admin']||(bool)($source['break_glass']??false))throw new RuntimeException('cannot_merge_privileged_source');
        $snapshot=['user'=>$source,'groups'=>$this->db->all('SELECT group_id FROM group_members WHERE user_id=?',[$sourceUserId]),'roles'=>$this->db->all('SELECT role_id FROM user_system_roles WHERE user_id=?',[$sourceUserId]),'applications'=>$this->db->all('SELECT * FROM application_users WHERE user_id=?',[$sourceUserId]),'app_roles'=>$this->db->all('SELECT application_id,app_role_id FROM app_user_roles WHERE user_id=?',[$sourceUserId])];
        $this->db->transaction(function()use($sourceUserId,$targetUserId,$actorUserId,$reason,$target,$snapshot):void{
            $this->db->execute('INSERT IGNORE INTO group_members(group_id,user_id) SELECT group_id,? FROM group_members WHERE user_id=?',[$targetUserId,$sourceUserId]);$this->db->execute('INSERT IGNORE INTO user_system_roles(user_id,role_id) SELECT ?,role_id FROM user_system_roles WHERE user_id=?',[$targetUserId,$sourceUserId]);
            foreach($this->db->all('SELECT * FROM application_users WHERE user_id=?',[$sourceUserId]) as $grant){$existing=$this->db->one('SELECT 1 FROM application_users WHERE application_id=? AND user_id=?',[(int)$grant['application_id'],$targetUserId]);if(!$existing)$this->db->execute('INSERT INTO application_users(application_id,user_id,enabled,valid_from,valid_until,grant_source,revoked_at,revoke_reason,created_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)',[(int)$grant['application_id'],$targetUserId,(int)$grant['enabled'],$grant['valid_from'],$grant['valid_until'],$grant['grant_source'],$grant['revoked_at'],$grant['revoke_reason'],$grant['created_at'],$grant['created_by']]);}
            $this->db->execute('INSERT IGNORE INTO app_user_roles(application_id,user_id,app_role_id,created_at,created_by) SELECT application_id,?,app_role_id,created_at,created_by FROM app_user_roles WHERE user_id=?',[$targetUserId,$sourceUserId]);$this->db->execute('INSERT IGNORE INTO application_owners(application_id,user_id,is_primary,created_at,created_by) SELECT application_id,?,0,created_at,created_by FROM application_owners WHERE user_id=?',[$targetUserId,$sourceUserId]);
            foreach($this->db->all('SELECT * FROM application_admins WHERE user_id=?',[$sourceUserId]) as $row){if(!$this->db->one('SELECT 1 FROM application_admins WHERE application_id=? AND user_id=?',[(int)$row['application_id'],$targetUserId]))$this->db->execute('INSERT INTO application_admins(application_id,user_id,permissions_json,created_at,created_by) VALUES(?,?,?,?,?)',[(int)$row['application_id'],$targetUserId,$row['permissions_json'],$row['created_at'],$row['created_by']]);}
            foreach($this->db->all('SELECT attribute_key,attribute_value,source FROM user_attributes WHERE user_id=?',[$sourceUserId]) as $attr)$this->db->execute('INSERT IGNORE INTO user_attributes(user_id,attribute_key,attribute_value,source) VALUES(?,?,?,?)',[$targetUserId,$attr['attribute_key'],$attr['attribute_value'],$attr['source']]);
            foreach($this->db->all('SELECT * FROM user_application_preferences WHERE user_id=?',[$sourceUserId]) as $pref){$existing=$this->db->one('SELECT * FROM user_application_preferences WHERE user_id=? AND application_id=?',[$targetUserId,(int)$pref['application_id']]);if(!$existing)$this->db->execute('INSERT INTO user_application_preferences(user_id,application_id,favorite,sort_order,created_at) VALUES(?,?,?,?,?)',[$targetUserId,(int)$pref['application_id'],(int)$pref['favorite'],(int)$pref['sort_order'],$pref['created_at']]);elseif((bool)$pref['favorite'])$this->db->execute('UPDATE user_application_preferences SET favorite=1 WHERE user_id=? AND application_id=?',[$targetUserId,(int)$pref['application_id']]);}
            foreach($this->db->all('SELECT * FROM user_emails WHERE user_id=?',[$sourceUserId]) as $email){$existing=$this->db->one('SELECT id FROM user_emails WHERE email=? AND user_id=?',[$email['email'],$targetUserId]);if($existing){$this->db->execute('DELETE FROM user_emails WHERE id=?',[(int)$email['id']]);continue;}$this->db->execute('UPDATE user_emails SET user_id=?,is_primary=0 WHERE id=?',[$targetUserId,(int)$email['id']]);}
            $this->db->execute('UPDATE external_identities SET user_id=? WHERE user_id=?',[$targetUserId,$sourceUserId]);$this->db->execute('UPDATE oauth_access_tokens SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL',[$sourceUserId]);$this->db->execute('UPDATE oauth_refresh_tokens SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL',[$sourceUserId]);$this->db->execute('UPDATE oidc_sessions SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL',[$sourceUserId]);$this->db->execute('UPDATE user_application_consents SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL',[$sourceUserId]);
            $this->db->execute('DELETE FROM application_users WHERE user_id=?',[$sourceUserId]);$this->db->execute('DELETE FROM app_user_roles WHERE user_id=?',[$sourceUserId]);$this->db->execute('DELETE FROM group_members WHERE user_id=?',[$sourceUserId]);$this->db->execute('DELETE FROM user_system_roles WHERE user_id=?',[$sourceUserId]);$this->db->execute('DELETE FROM application_owners WHERE user_id=?',[$sourceUserId]);$this->db->execute('DELETE FROM application_admins WHERE user_id=?',[$sourceUserId]);
            $replacement='merged-'.$sourceUserId.'-'.time().'@invalid.local';$this->db->execute("UPDATE users SET name=?,username=NULL,email=?,enabled=0,lifecycle_status='disabled',account_ends_at=NOW() WHERE id=?",['Merged into user #'.$targetUserId,$replacement,$sourceUserId]);
            $this->db->execute('INSERT INTO user_merge_history(source_user_id,target_user_id,source_snapshot_json,merged_by) VALUES(?,?,?,?)',[$sourceUserId,$targetUserId,json_encode($snapshot,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),$actorUserId]);$this->audit->write('users.merged','success',$actorUserId,$targetUserId,null,$reason,['source_user_id'=>$sourceUserId,'target_user_id'=>$targetUserId]);
        });
    }
}
